apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-notification-service-secret
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  NOTIFICATION_DB_DSN: {{ .Values.secret.dbDSN | quote }}
  NOTIFICATION_AMQP_URL: {{ .Values.secret.amqpURL | quote }}
  SMTP_HOST: {{ .Values.secret.smtpHost | quote }}
  SMTP_PORT: {{ .Values.secret.smtpPort | quote }}
  SMTP_USER: {{ .Values.secret.smtpUser | quote }}
  SMTP_PASSWORD: {{ .Values.secret.smtpPassword | quote }}
