apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notification-service-server
  labels:
    app.kubernetes.io/name: notification-service-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: notification-service-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
